src/comani/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('', include('accounts.urls')),
    path('', include('catalog.urls')),
    path('', include('shopping_cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

src/shopping_cart/urls.py
from django.urls import path, include

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    purchase_success
)

urlpatterns = [
    path('cart/', include(([
        path('add-to-cart/<int:item_id>/', add_to_cart, name="add_to_cart"),
        path('order-summary/', order_details, name="order_summary"),
        path('success/', purchase_success, name='purchase_success'),
        path('item/delete/<int:item_id>/', delete_from_cart, name='delete_item'),
    ], 'shopping_cart'), namespace='shopping_cart')),
]

src/templates/partials/footer.html
<div class="footer black-bg">
    COMANI &copy;
    <script>
        document.write(new Date().getFullYear())
    </script>
</div>

src/templates/partials/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible mt-5" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

src/templates/partials/navbar.html
{% load cart_template_tag %}

<nav class="navbar fixed-top navbar-expand-lg navbar-dark black-bg">
    <a class="navbar-brand" href="#">Comani</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.resolver_match.url_name == 'home' %}active{% endif %}">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.resolver_match.url_name == 'product-list' %}active{% endif %}">
                <a class="nav-link" href="{% url 'products:product-list' %}">Shop</a>
            </li>
            <li class="nav-item {% if request.resolver_match.url_name == 'service-list' %}active{% endif %}">
                <a class="nav-link" href="{% url 'services:service-list' %}">Service</a>
            </li>
            {% if request.user.is_authenticated %}
                {% comment %} <li class="nav-item {% if request.resolver_match.url_name == 'wall' %}active{% endif %}">
                    <a class="nav-link" href="#">{{request.user.name}}</a>
                </li> {% endcomment %}
                {% if request.user.is_customer %}
                <li class="nav-item">
                    <a href="#" data-toggle="popover" data-placement="bottom" data-toggle="popover" title="Shopping Cart">
                        <i class="fas fa-shopping-cart"></i>
                        {% for order in request.user.customer.orders.all %}
                            {% if order.is_fulfilled == False %}
                                <span class="badge badge-light">
                                {{ request.user|cart_item_count }}
                                </span>
                            {% endif %}
                        {% endfor %}
                    </a>
                    <!-- loaded popover content -->
                    <div id="popover-content" style="display: none">
                        <ul class="list-group custom-popover">
                            {% for order in request.user.customer.orders.all %}
                                {% if order.is_fulfilled == False %}
                                    <li class="list-group-item">
                                    {% for item in order.items.all %}
                                        {{ item.product.name }} - {{ item.product.price }}
                                    {% endfor %}
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </li>
                {% endif %}
                {% if request.user.is_vendor %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'vendors:dashboard' request.user.vendor.slug %}">Dashboard</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                
            {% else %}
                <li class="nav-item {% if request.resolver_match.url_name == 'user_signup' %}active{% endif %}">
                <a class="nav-link" href="{% url 'user_signup' %}">Signup</a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == 'login' %}active{% endif %}">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <div class="input-group my-2">
                <input type="text" class="form-control" id="nav-search-form" placeholder="Search" aria-label="Search" aria-describedby="nav-search-btn">
                <div class="input-group-append">
                    <button class="btn whiskey-sour-bg text-white" type="button" id="nav-search-btn"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
    </div>
</nav>

src/templates/partials/product-card.html
<div class="card product-card" style="">
    <div class="card-body">
        <div class="row">
            <div class="col-md-7">
                {% for photo in object.album.photos.all %}
                    {% if photo.default and photo.album.name == object.album.name  %}
                        <img src="{{ MEDIA_URL }}{{photo.url}}" class="card-img-top" alt="...">
                    {% endif %}
                {% endfor %}
            </div>
            <div class="col-md-5">
                <div class="product">
                    <p>{{ object.category.name }}</p>
                    <h1>{{ object.name }}</h1>
                    <h2>${{ object.price }}</h2>
                    <p class="desc">{{ object.description|truncatechars:50 }}</p>
                    {% comment %} { {% endcomment %}
                    <div class="">
                        {% if object in current_order_products %}
                            <a href="{% url 'shopping_cart:order_summary' %}" class="text-center buttons add rounded-pill">Go to Cart</a>
                        {% else %}
                            <a href="{% url 'shopping_cart:add_to_cart' object.id %}" class="text-center buttons add rounded-pill">Add to Cart</a>
                        {% endif %}
                        <button class="buttons like rounded-circle"><span>♥</span></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>