src/comani/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('', include('accounts.urls')),
    path('', include('catalog.urls')),
    path('', include('shopping_cart.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/events/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('events/', include(([
        path('', views.events_list, name='events-list'),
        path('<int:pk>/', views.user_events, name='user-events'),
        path('<int:pk>/', views.event_details, name='event-view'),
        path('create/', views.event_create, name='event-new'),
    ], 'events'), namespace='events')),
]

src/pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

src/events/models.py
import uuid
from django.db import models
from django.shortcuts import reverse

from accounts.models import Customer, Vendor
from catalog.models import Product

# Create your models here.
class Event(models.Model):
    slug = models.SlugField(unique=True, default=uuid.uuid1, blank=True)
    name = models.CharField(max_length=50, blank=True)
    details = models.TextField(blank=True)
    venue = models.CharField(max_length=200, blank=True)
    date = models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', blank=True)
    time = models.TimeField(help_text='Please use the following format: <em>HH:MM:SS<em>', blank=True)
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE, related_name='events', blank=True)
    attendees = models.ManyToManyField(Customer, related_name='events', blank=True)

    class Meta:
        verbose_name = 'event'
        verbose_name_plural = 'events'
        ordering = ['date', 'time']

    def get_absolute_url(self):
        return reverse('events:event-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

    def get_number_of_attendees(self):
        return self.attendees.all().count()

class Ticket(models.Model):
    slug = models.SlugField(unique=True, default=uuid.uuid1, blank=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="tickets", blank=True)
    product = models.OneToOneField(Product, on_delete=models.CASCADE, blank=True)

    def __str__(self):
        return self.product.name

src/events/forms.py
from django import forms

from .models import Event


class EventForm(forms.ModelForm):
    name = forms.CharField(max_length=50, min_length=3, widget=forms.TextInput(attrs={'class':'form-control'}))
    venue = forms.CharField(max_length=200, min_length=3, widget=forms.TextInput(attrs={'class':'form-control'}))
    time = forms.TimeField(widget=forms.TimeInput(attrs={'class':'form-control', 'type': 'time'}))
    date = forms.DateField(widget=forms.DateInput(attrs={'class':'form-control', 'type': 'date'}))
    details = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}))

    class Meta:
        model = Event
        fields = ('name', 'details', 'venue', 'time', 'date',)

src/events/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .forms import EventForm
from .models import Event
from accounts.models import Customer, Vendor

# Create your views here.
def events_list(request, template_name='events/events_list.html'):
    events = Event.objects.all()
    data = {}
    data['events'] = events
    return render(request, template_name, data)

def user_events(request, pk, template_name='events/events_list.html'):
    vendor = get_object_or_404(Vendor, pk=pk)
    events = Event.objects.filter(vendor=vendor)
    data = {}
    data['events'] = events
    return render(request, template_name, data)

def event_create(request, template_name='events/events_form.html'):
    form = EventForm(request.POST or None)
    if form.is_valid():
        c = form.save(commit=False)
        c.vendor = request.user.vendor
        c.save()
        return redirect('events:event-view', c.id)
    return render(request, template_name, {'form':form})

def event_details(request, pk, template_name='events/event_details.html'):
    event = get_object_or_404(Event, pk=pk)
    data = {}
    data['event'] = event
    return render(request, template_name, data)

src/events/templates/events/event_details.html
{% extends 'base.html' %}

{% block content %}
    <div class='container my-5'>
        <h1 class='pt-2'>{{ event.name }}</h1>
        <a href="{% url 'events:user-events' request.user.id %}" class='btn btn-primary btn-block'>My Events</a>
        <p>{{ event.details|safe }}</p>
    </div>
{% endblock content %}

src/events/templates/events/events_form.html
{% extends 'base.html' %}

{% block content %}
    {{ form.media }}
    <div class='container my-5'>
        <h2>Add a new product</h2>
        <form method="post" novalidate>
            {% csrf_token %}
            <div class="form-group">
                {{ form.name.errors }}
                <label for="{{ form.name.id_for_label }}">Name:</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                {{ form.venue.errors }}
                <label for="{{ form.venue.id_for_label }}">Venue:</label>
                {{ form.venue }}
            </div>
            <div class="form-group">
                {{ form.details.errors }}
                <label for="{{ form.details.id_for_label }}">Details:</label>
                {{ form.details }}
            </div>
            <div class="form-group">
                {{ form.date.errors }}
                <label for="{{ form.date.id_for_label }}">Date:</label>
                {{ form.date }}
            </div>
            <div class="form-group">
                {{ form.time.errors }}
                <label for="{{ form.time.id_for_label }}">Time:</label>
                {{ form.time }}
            </div>
            <button type="submit" class="btn btn-primary btn-round">Save</button>
        </form>
    </div>
{% endblock content %}

src/events/templates/events/events_list.html
{% extends 'base.html' %}

{% block content %}
    <div class='container my-5'>
        <h1 class='pt-3'>Events</h1>
        <a href="{% url 'events:event-new' %}" class='btn btn-primary btn-block'>Create Event</a>
        <div class='my-2'>
        {% for event in events %}
            <p><a href="{% url 'events:event-view' event.id %}">{{ event.name }} @ {{ event.venue }}</a></p>
        {% empty %}
            <p>No events available.</p>
        {% endfor %}
        </div>
    </div>
{% endblock content %}